### ISSUE TITLE
Connecting with Pulse Audio from service

### ISSUE THREAD

**Issue by NicholasMamo** [mhthies/pulsectl-asyncio#12]
Hi! I'm using the library to create an Ubuntu service that connects with Pulse Audio and automatically ducks music applications when something else is running.

When I run the script, it runs perfectly, but when I run it as a service, it fails to connect with the Pulse Audio server. Any ideas why please? This is the traceback:

```
Mar 08 21:52:11 nitro python[47240]: Traceback (most recent call last):
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/venv/lib/python3.8/site-packages/pulsectl_asyncio/pulsectl_async.py", line 129, in connect
Mar 08 21:52:11 nitro python[47240]:     c.pa.context_connect(self._ctx, self.server, flags, None)
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/venv/lib/python3.8/site-packages/pulsectl/_pulsectl.py", line 673, in _wrapper
Mar 08 21:52:11 nitro python[47240]:     raise self.CallError(*err)
Mar 08 21:52:11 nitro python[47240]: pulsectl._pulsectl.CallError: ('pa_context_connect', (<pulsectl._pulsectl.LP_PA_CONTEXT object at 0x7ff96e34aa40>, None, 1, None), -1, 'Connection refused [pulse errno 6]')
Mar 08 21:52:11 nitro python[47240]: The above exception was the direct cause of the following exception:
Mar 08 21:52:11 nitro python[47240]: Traceback (most recent call last):
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/main.py", line 81, in <module>
Mar 08 21:52:11 nitro python[47240]:     loop.run_until_complete(main())
Mar 08 21:52:11 nitro python[47240]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
Mar 08 21:52:11 nitro python[47240]:     return future.result()
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/main.py", line 17, in main
Mar 08 21:52:11 nitro python[47240]:     async with pulsectl_asyncio.PulseAsync('volume-increaser') as pulse:
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/venv/lib/python3.8/site-packages/pulsectl_asyncio/pulsectl_async.py", line 163, in __aenter__
Mar 08 21:52:11 nitro python[47240]:     await self.connect()
Mar 08 21:52:11 nitro python[47240]:   File "/path/to/venv/lib/python3.8/site-packages/pulsectl_asyncio/pulsectl_async.py", line 136, in connect
Mar 08 21:52:11 nitro python[47240]:     raise PulseError('Failed to connect to pulseaudio server') from e
Mar 08 21:52:11 nitro python[47240]: pulsectl.pulsectl.PulseError: Failed to connect to pulseaudio server
```

This is my service:

```
[Unit]
Description=Auto-ducker
After=multi-user.target
[Service]
Type=simple
Restart=always
ExecStart=/path/to/venv/bin/python /path/to/main.py
[Install]
WantedBy=multi-user.target
```

I have tried:

- Specifying the server manually. When I run  pulse.server_info(), the server name shows as 'pulseaudio'. When I specify the server (`async with pulsectl_asyncio.PulseAsync('volume-increaser', server='pulseaudio') as pulse:`), it fails to connect.
- Running the service with `User=nicholas` and `Group=nicholas`, my user and user group.

In both cases, the server fails to connect to the pulseaudio server.

**Comment by mhthies** [comment]
This is more a PulseAudio / libpulse usage issue than an issue with this library.

I'm not 100% sure about the mechanism, how libpulse detects the correct socket of the PulseAudio server. I would assume that, if you run PulseAudio in user mode for your specific user (as opposed to system mode), you need to
a) run your service as your user (for access privileges to the PulseAudio socket)
b) set the XDG_RUNTIME_DIR to your user's runtime directory.
but I'm not sure about this.

You should probably google how to run a PulseAudio client as a systemd service. (pulsectl-asyncio is not different from any other native PulseAudio client, based on libpulse).

Maybe running the service as a systemd user unit could be a solution?

**Comment by NicholasMamo** [comment]
I know it's not a library issue, but I thought maybe you had met the issue before. I've continued to experiment and it gives me the same error even if I try to run it as my own user through sudo: `sudo -H -u nicholas bash -c '/home/nicholas/GitHub/auto-ducker/venv/bin/python /home/nicholas/GitHub/auto-ducker/main.py'`. Anyway, I'll close the issue and ask on Ask Ubuntu.

Thank you for the work on the library!

**Comment by NicholasMamo** [comment]
I know it's not a library issue, but I thought maybe you had met the issue before. I've continued to experiment and it gives me the same error even if I try to run it as my own user through sudo: `sudo -H -u nicholas bash -c '/home/nicholas/GitHub/auto-ducker/venv/bin/python /home/nicholas/GitHub/auto-ducker/main.py'`. Anyway, I'll close the issue and ask on Ask Ubuntu.

Thank you for the work on the library!
