### ISSUE TITLE
Deprecation of module inspect on python 3.11

### ISSUE THREAD

**Issue by theRealCarneiro** [mhthies/pulsectl-asyncio#13]
Python 3.11.3 on Arch Linux
```
File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/__init__.py", line 1, in <module>
    from .pulsectl_async import PulseAsync
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 66, in <module>
    class PulseAsync(object):
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 311, in PulseAsync
    card_profile_set_by_index = _pulse_method_call(
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 303, in _pulse_method_call
    func_args = list(inspect.getargspec(func or (lambda: None)))
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by mhthies** [comment]
Hi, this should already be fixed since [version 1.0.0](https://github.com/mhthies/pulsectl-asyncio/releases/tag/v1.0.0) of this package. Did try the latest release?

**Comment by theRealCarneiro** [comment]
I use the aur version (tried rebuild, clean install and stuff), it must be out of date, and the -git version doesn't build properly, guess ill fallback to the pipy version

**Comment by theRealCarneiro** [comment]
I use the aur version (tried rebuild, clean install and stuff), it must be out of date, and the -git version doesn't build properly, guess ill fallback to the pipy version

**Comment by mhthies** [comment]
Oh, I didn't know someone built an AUR package from this Python package. Could have done that myself, I guess, but I wasn't aware that people would use and install it that way.

Can you please flag the AUR package as "out of date" so the maintainer can look after packaging the latest version? If they do not react to it; I may look if I can and should take the maintainership of the AUR package.

**Comment by theRealCarneiro** [comment]
Done it so, let's hope they fix it soon
