### ISSUE TITLE
PulseAudio AudioStream

### ISSUE THREAD

**Issue by RESP3CT88** [mhthies/pulsectl-asyncio#4]
Can this library be used to play a wav file and capture the audiostream's playback/recording amplitude?
https://freedesktop.org/software/pulseaudio/doxygen/streams.html

I need to do something like this
https://thumbs.gfycat.com/AgonizingThinAustralianfreshwatercrocodile-max-1mb.gif

**Comment by mhthies** [comment]
Audio playback is not captured by the library yet. You may want to take a look at [this fork of the original pulsectl library](https://github.com/SoundWall/python-pulse-control/blob/ac371fb/pulsectl/pulsectl.py#L979-L1053). Maybe you can use this code for audio playback.

Monitoring of a stream's amplitude/level has just been released in this library (including sources, sinks' sum signals and individual playback streams). Here's the brand new `subscribe_peak_sample()` method: https://github.com/mhthies/pulsectl-asyncio/blob/main/pulsectl_asyncio/pulsectl_async.py#L532
There's not much documentation yet, but the docstring should explain the relevant features and usage.

**Comment by RESP3CT88** [comment]
Awesome thanks, I will try it out!

**Comment by RESP3CT88** [comment]
Great I have the playback levels working, but I can't seem to get the microphone input levels fully working. It runs and shows the mic level for about 5 seconds and then stops. I would like it to run indefinitely.

I'm running on _Python 3.8, Ubuntu 20.04, x86_64_

Code:
```
import asyncio
import pulsectl_asyncio

async def main():
    pulse = pulsectl_asyncio.PulseAsync('my-client-name')
    await pulse.connect()

    # List sinks
    si = await pulse.source_list()

    # for debugging
    print(si)

    # Output mic level
    async for volume in pulse.subscribe_peak_sample(si[2].name, rate=5):
                          print("volume =", volume)

    pulse.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```


Output:
```
ubuntu@ubuntu:~/Test2/main$ python3 main.py 
[<PulseSourceInfo at 7f151f7642e0 - description='Monitor of Hawaii HDMI Audio [Radeon R9 290/290X / 390/390X] Digital Stereo (HDMI)', index=0, mute=0, name='alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor', channels=2, volumes=[100% 100%]>, <PulseSourceInfo at 7f151f7643d0 - description='Monitor of HyperX Cloud Flight Wireless Headset Analog Stereo', index=1, mute=0, name='alsa_output.usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00.analog-stereo.monitor', channels=2, volumes=[100% 100%]>, <PulseSourceInfo at 7f151f7644c0 - description='HyperX Cloud Flight Wireless Headset Mono', index=2, mute=0, name='alsa_input.usb-Kingston_HyperX_Cloud_Flight_Wireless_Headset-00.mono-fallback', channels=1, volumes=[79%]>, <PulseSourceInfo at 7f151f7645b0 - description='Monitor of Built-in Audio Digital Stereo (IEC958)', index=3, mute=0, name='alsa_output.pci-0000_00_1f.3.iec958-stereo.monitor', channels=2, volumes=[100% 100%]>]
volume = 0.00042724609375
volume = 0.00042724609375
volume = 0.001312255859375
volume = 0.001495361328125
volume = 0.00079345703125
volume = 0.000518798828125
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 0.0
volume = 6.103515625e-05
volume = 0.23785400390625
volume = 0.126495361328125
volume = 0.076171875
volume = 0.074676513671875
volume = 0.15069580078125
volume = 0.002288818359375


```

**Comment by mhthies** [comment]
Hm. Interesting. The code is more or less copied from pulsectl and I didn't test it with a PulseAudio source (i.e. microphone input) yet.
I'll take a look and try to figure it out …

**Comment by mhthies** [comment]
Okay. The problem was, that I copy-and-pasted the `PA_STREAM_DONT_INHIBIT_AUTO_SUSPEND` flag from pulsectl's code. This results in PulseAudio autosuspending the source device even though our record/peak-detection stream is still active, as long as no other application is recording or monitoring audio from that source.

I removed this flag, since I don't see any reason to use it here. IMHO, we want the device to stay active as long as we want to monitor its input signal. (pavucontrol actually handles this a bit more elaborate by allowing suspension but resetting it's visual level meters when the device is suspended)

**Comment by RESP3CT88** [comment]
Excellent, thanks for the explanation, it works perfectly now.
