### ISSUE TITLE
time_t portability

### ISSUE THREAD

**Issue by the-nic** [mhthies/pulsectl-asyncio#5]
For your FFI you define timeval as follows:
```python
class timeval(c.Structure):
    _fields_ = [
        ('tv_sec', c.c_longlong),
        ('tv_usec', c.c_long),
    ]
```
This is, unfortunately not portable as `tv_sec` is of type `time_t` which may also be `c_long` (as it is in my case), and then overflowing like this later on:
```
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
OverflowError: timestamp too large to convert to C _PyTime_t
```
because the upper bytes are undefined. Forcing  `c_long` instead helps in my case but i suspect this is also not more portable - even though one might get away with it...

**Comment by mhthies** [comment]
This sounds like an `& 0xffffffff` would work out as a dirty hack until 2038. We would still read 4 bytes too much on systems with 32bit time_t but zero out these bytes. However, I will try to figure out if there's a better portable way to read a time_t/timeval from Python.

**Comment by mhthies** [comment]
It seems there is no straight-forward way of getting the type (or size) of `time_t` from Python. My current approach is to find out the size of `time_t` via trial and error:

Could you check if the following code raises an `OverfowError` on your platform?
```python
import time
time.gmtime(2 ** 33)
```

I assume it does. Then, I will use this as a check to distinguish bettween `c_long` and `c_longlong`.

**Comment by the-nic** [comment]
```
>>> time.gmtime(2 ** 33)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range for platform time_t
```

**Comment by the-nic** [comment]
Try the following:
```python
import sysconfig
sysconfig.get_config_var('SIZEOF_TIME_T')
```
which returns the size in bytes for `time_t`, 8 for 64bit systems, 4 for 32 bit systems


One could even exend this as follows:
```python
time_t_size = sysconfig.get_config_var('SIZEOF_TIME_T')
if time_t_size == sysconfig.get_config_var('SIZEOF_LONG_LONG'):
   c_time_t = c.c_longlong
elif time_t_size == sysconfig.get_config_var('SIZEOF_LONG'):
   c_time_t = c.c_long
else:
   # error
```

**Comment by mhthies** [comment]
Oh, nice! Thanks for the hint! I didn't know about this module and its way cleaner than my try-except hack.

I like the `sysconfig.get_config_var('SIZEOF_TIME_T') == sysconfig.get_config_var('SIZEOF_LONG')` solution. It does not catch `time_t` types other than signed integers correctly – such as float or unsigned integers – which are allowed according to the C standard but sufficiently obscure to ignore them.
